# Generated by Django 5.2.3 on 2025-06-30 05:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('image', models.ImageField(max_length=255, upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('image_width', models.PositiveIntegerField()),
                ('image_height', models.PositiveIntegerField()),
                ('prediction_class', models.CharField(choices=[('normal', 'Normal'), ('pneumonia', 'Pneumonia')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('model_version', models.CharField(default='resnet50-v1.0', max_length=50)),
                ('processing_time', models.FloatField()),
                ('raw_probabilities', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'analysis_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key', '-created_at'], name='analysis_re_session_5e2ab8_idx'), models.Index(fields=['status', 'created_at'], name='analysis_re_status_68582e_idx'), models.Index(fields=['prediction_class', 'confidence_score'], name='analysis_re_predict_0ca39f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('total_predictions', models.PositiveIntegerField(default=0)),
                ('avg_processing_time', models.FloatField(default=0.0)),
                ('avg_confidence_score', models.FloatField(default=0.0)),
                ('normal_predictions', models.PositiveIntegerField(default=0)),
                ('pneumonia_predictions', models.PositiveIntegerField(default=0)),
                ('high_confidence_predictions', models.PositiveIntegerField(default=0)),
                ('first_prediction', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'model_metrics',
                'unique_together': {('model_name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('analysis_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', '-created_at'], name='system_logs_level_cded50_idx'), models.Index(fields=['category', '-created_at'], name='system_logs_categor_b284e6_idx'), models.Index(fields=['session_key', '-created_at'], name='system_logs_session_b9935c_idx')],
            },
        ),
    ]
