# Generated by Django 5.2.3 on 2025-07-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="accession_number",
            field=models.CharField(
                blank=True,
                help_text="Radiology accession number",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="clinical_indication",
            field=models.TextField(
                blank=True, help_text="Clinical reason for the imaging study", null=True
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="department",
            field=models.CharField(
                blank=True,
                help_text="Hospital department (e.g., Radiology, Emergency)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="dicom_metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional DICOM metadata tags"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="equipment_manufacturer",
            field=models.CharField(
                blank=True,
                help_text="X-ray equipment manufacturer",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="equipment_model",
            field=models.CharField(
                blank=True, help_text="X-ray equipment model", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="exposure_time",
            field=models.FloatField(
                blank=True, help_text="Exposure time in seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="image_orientation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PA", "Posterior-Anterior"),
                    ("AP", "Anterior-Posterior"),
                    ("LAT", "Lateral"),
                    ("OBLIQUE", "Oblique"),
                    ("DECUBITUS", "Decubitus"),
                    ("OTHER", "Other"),
                ],
                help_text="X-ray view/orientation",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="institution_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the medical institution",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="is_dicom_source",
            field=models.BooleanField(
                default=False, help_text="Indicates if original file was DICOM format"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="kvp",
            field=models.FloatField(
                blank=True, help_text="X-ray tube voltage (kVp)", null=True
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="mas",
            field=models.FloatField(
                blank=True, help_text="Milliampere-seconds (mAs)", null=True
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="modality",
            field=models.CharField(
                choices=[
                    ("CR", "Computed Radiography"),
                    ("DX", "Digital Radiography"),
                    ("DR", "Digital Radiography"),
                    ("XR", "Conventional X-Ray"),
                    ("MG", "Mammography"),
                    ("CT", "Computed Tomography"),
                    ("MR", "Magnetic Resonance"),
                    ("OTHER", "Other"),
                ],
                default="CR",
                help_text="Imaging modality used",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="patient_age",
            field=models.PositiveIntegerField(
                blank=True, help_text="Patient age at time of study", null=True
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="patient_id",
            field=models.CharField(
                blank=True,
                help_text="Patient identification number (anonymized for privacy)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="patient_sex",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("U", "Unknown"),
                ],
                help_text="Patient biological sex",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="referring_physician",
            field=models.CharField(
                blank=True,
                help_text="Name of the referring physician",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="study_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the medical study was performed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="study_id",
            field=models.CharField(
                blank=True,
                help_text="Unique study identifier",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="technician_id",
            field=models.CharField(
                blank=True,
                help_text="ID of the technician who performed the imaging",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="analysisresult",
            index=models.Index(
                fields=["patient_id", "-study_date"],
                name="analysis_re_patient_e65ef2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analysisresult",
            index=models.Index(
                fields=["study_id"], name="analysis_re_study_i_ec2972_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysisresult",
            index=models.Index(
                fields=["accession_number"], name="analysis_re_accessi_f32e02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysisresult",
            index=models.Index(
                fields=["technician_id", "-created_at"],
                name="analysis_re_technic_f9b9f2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analysisresult",
            index=models.Index(
                fields=["study_date", "modality"], name="analysis_re_study_d_60be1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysisresult",
            index=models.Index(
                fields=["institution_name", "-created_at"],
                name="analysis_re_institu_c1e976_idx",
            ),
        ),
    ]
