# Generated by Django 5.2.3 on 2025-07-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_medical_metadata"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="analysisresult",
            name="analysis_re_patient_e65ef2_idx",
        ),
        migrations.RemoveIndex(
            model_name="analysisresult",
            name="analysis_re_study_i_ec2972_idx",
        ),
        migrations.RemoveIndex(
            model_name="analysisresult",
            name="analysis_re_accessi_f32e02_idx",
        ),
        migrations.RemoveIndex(
            model_name="analysisresult",
            name="analysis_re_technic_f9b9f2_idx",
        ),
        migrations.RemoveIndex(
            model_name="analysisresult",
            name="analysis_re_study_d_60be1d_idx",
        ),
        migrations.RemoveIndex(
            model_name="analysisresult",
            name="analysis_re_institu_c1e976_idx",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="accession_number",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="clinical_indication",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="department",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="dicom_metadata",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="equipment_manufacturer",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="equipment_model",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="exposure_time",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="image_orientation",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="institution_name",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="is_dicom_source",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="kvp",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="mas",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="modality",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="patient_age",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="patient_id",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="patient_sex",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="referring_physician",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="study_date",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="study_id",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="technician_id",
        ),
    ]
